name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # This allows you to access your repository files, including the Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true  # Set to true because you are pushing the image to Docker Hub
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Run Docker container
        run: |
          docker run ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Verify Docker container output
        run: |
          docker logs $(docker ps -lq)  # This captures and prints the logs of the last container
